name: Ragu Audit Ticket
description: Flag issues with Ragu as part of the QEDIT audit
body:
  - type: dropdown
    id: crate
    attributes:
      label: Crate
      description: Which Ragu crate is this related to?
      options:
        - ragu_arithmetic
        - ragu_circuits
        - ragu_core
        - ragu_gadgets
        - ragu_macros
        - ragu_pasta
        - ragu_pcd
        - ragu_primitives
      default: 0
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Select the issue severity.
      options:
        - low
        - medium
        - high
        - critical
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A concise description of the issue in the Ragu code. If you describe a bug, include environment details and steps to reproduce.
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code
      description: Relevant code and any new tests that reproduce the issue.
      render: shell
      value: |
        File name: `crates/.../src/...`

        ```rust
        // existing code
        ```

        ```rust
        // new test(s) demonstrating the issue
        ```
    validations:
      required: false

  - type: textarea
    id: recommendations
    attributes:
      label: Recommendations
      description: Provide recommendations for resolution / remediation.
    validations:
      required: false
